name: Pull Request Stats init

on:
  pull_request:
    types: [opened]

jobs:
  stats:
    runs-on: ubuntu-latest
    steps:
      - name: Run pull request stats
        uses: flowwer-dev/pull-request-stats@master
        with:
          repositories: "pr-stats-data"
          webhook: "https://hooks.zapier.com/hooks/catch/123456/XXXXXXXX"
          # webhook: ${{ secrets.WEBHOOK_URL }} You may want to store this value as a secret.
