name: Pull Request Stats

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  stats:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Run pull request stats
        uses: flowwer-dev/pull-request-stats@master
        with:
          repositories: "Venkadeshkissflow/pr-stats-data"
          webhook: "https://helloworld-qolwwtnb6a-uc.a.run.app/"
          period: 2
          charts: true
          disableLinks: true
