name: Pull Request Stats

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Run pull request stats
        uses: flowwer-dev/pull-request-stats@master
        with:
          repositories: "Venkadeshkissflow/pr-stats-data"
          webhook: "https://helloworld-qolwwtnb6a-uc.a.run.app/"
          limit: 1
          sortBy: "TIME"
          period: 1
          charts: true
          disableLinks: true
